### ISSUE TITLE
Introduce `dprint` for consistency

### ISSUE THREAD

**Issue by azzamsa** [hds/lunch.rs#1]
Hi.

I would like to introduce `drpint`. A formatted written in Rust to keep code consistency. Having built in Rust, the local installation is just a single step `cargo install`.

Thanks for lunch.rs! 🏅

**Comment by azzamsa** [comment]
I will wait until this issue resolves

- https://github.com/dprint/dprint-plugin-prettier/issues/60

**Comment by azzamsa** [comment]
I will only use `dprint` for formatting markdown and toml files. I will use `prettier` directly for HTML and CSS files.
This PR #4  is ready for review.

**Comment by hds** [comment]
@azzamsa #4 is merged so this is closed now I believe. Thanks for your contribution, I'll let you close the issue if you're happy with things.

**Comment by azzamsa** [comment]
Thank you!
